
package nezet;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modell.Auto;


public class AutoNezet extends javax.swing.JFrame {

    private List<Auto> autok;
    public AutoNezet() {
        initComponents();
        autok = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxRendszamDatum = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxDohanyzoe = new javax.swing.JCheckBox();
        jTextFieldFizetes = new javax.swing.JTextField();
        jTextFieldTav = new javax.swing.JTextField();
        jTextFieldOsszeg = new javax.swing.JTextField();
        jTextFieldBorravalo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemBetoltes = new javax.swing.JMenuItem();
        jMenuItemKilepes = new javax.swing.JMenuItem();
        jMenuFeladatok = new javax.swing.JMenu();
        jMenuItemOsszbevetel = new javax.swing.JMenuItem();
        jMenuItemLehetDohanyozni = new javax.swing.JMenuItem();
        jMenuItemLeghosszabbFuvar = new javax.swing.JMenuItem();
        jMenuItemKikDolgoztak = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rendszam/Datum"));

        jComboBoxRendszamDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRendszamDatumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxRendszamDatum, 0, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxRendszamDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setText("Fizetés");

        jLabel2.setText("Táv");

        jLabel3.setText("Összeg");

        jLabel4.setText("Borravaló");

        jCheckBoxDohanyzoe.setText("Dohányzó-e?");

        jTextFieldFizetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFizetesActionPerformed(evt);
            }
        });

        jMenuFile.setText("File");

        jMenuItemBetoltes.setText("Betöltés");
        jMenuItemBetoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBetoltesActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemBetoltes);

        jMenuItemKilepes.setText("Kilépés");
        jMenuItemKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKilepesActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemKilepes);

        jMenuBar1.add(jMenuFile);

        jMenuFeladatok.setText("Feladatok");

        jMenuItemOsszbevetel.setText("xyz-456 összbevetel");
        jMenuFeladatok.add(jMenuItemOsszbevetel);

        jMenuItemLehetDohanyozni.setText("minden autóban lehet dohányozni?");
        jMenuFeladatok.add(jMenuItemLehetDohanyozni);

        jMenuItemLeghosszabbFuvar.setText("leghosszabb fuvar");
        jMenuFeladatok.add(jMenuItemLeghosszabbFuvar);

        jMenuItemKikDolgoztak.setText("kik dolgoztak 2022.12.31-én?");
        jMenuFeladatok.add(jMenuItemKikDolgoztak);

        jMenuBar1.add(jMenuFeladatok);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFizetes)
                                    .addComponent(jTextFieldTav)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxDohanyzoe)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldOsszeg)
                                    .addComponent(jTextFieldBorravalo, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldFizetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldBorravalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jCheckBoxDohanyzoe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBetoltesActionPerformed
        try {
            List<String> sorok = Files.readAllLines(Path.of("fuvarok.txt"));
            for (int i = 2; i < sorok.size(); i++) {
                String sor = sorok.get(i);
                Auto auto = new Auto(sor);
                autok.add(auto);
                jComboBoxRendszamDatum.addItem(auto.getRendszam() + " / " + auto.getDatum());
            }
            megjelenit(autok.getFirst());
        } catch (IOException ex) {
            Logger.getLogger(AutoNezet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemBetoltesActionPerformed

    private void jComboBoxRendszamDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRendszamDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRendszamDatumActionPerformed

    private void jTextFieldFizetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFizetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFizetesActionPerformed

    private void jMenuItemKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKilepesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKilepesActionPerformed
    
    public void megjelenit(Auto auto){
    jTextFieldFizetes.setText(auto.getFizetesmod());
    jTextFieldTav.setText(auto.getTav()+"");
    jTextFieldOsszeg.setText(auto.getOsszeg()+"");
    jTextFieldBorravalo.setText(auto.getBorravalo()+"");
    jCheckBoxDohanyzoe.setSelected(auto.isDohanyzo());
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoNezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoNezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoNezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoNezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoNezet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxDohanyzoe;
    private javax.swing.JComboBox<String> jComboBoxRendszamDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFeladatok;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemBetoltes;
    private javax.swing.JMenuItem jMenuItemKikDolgoztak;
    private javax.swing.JMenuItem jMenuItemKilepes;
    private javax.swing.JMenuItem jMenuItemLeghosszabbFuvar;
    private javax.swing.JMenuItem jMenuItemLehetDohanyozni;
    private javax.swing.JMenuItem jMenuItemOsszbevetel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBorravalo;
    private javax.swing.JTextField jTextFieldFizetes;
    private javax.swing.JTextField jTextFieldOsszeg;
    private javax.swing.JTextField jTextFieldTav;
    // End of variables declaration//GEN-END:variables
}
